
Vagrant.configure("2") do |config|
    
    config.vm.box = "generic/ubuntu2204"
    config.disksize.size = "50GB"
    config.vm.synced_folder "openstack_deploy/", "/openstack_deploy/"
    config.vm.network :forwarded_port, guest: 80, host: 80
    config.vm.network :forwarded_port, guest: 8080, host: 8080

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 8096
        vb.cpus = 4
    end
end
  
  